layout: page
title: User Manual
permalink: /docs
baseurl: /rfallow # the subpath of your site, e.g. /blog
theme: minima
exclude: ["RFallow_manual"]

logourl: /www/images/rfallow_logo.png
logoalt: R-Fallow

navigation:
- text: Introduction
  internal: true
  url: ./

brand_color: "#DA253B"
