# Base configuration
exclude: ["README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DCgov Guides Template

# Author/Organization info to be displayed in the templates
author:
  name: Office of the Chief Technology Officer
  # url: http://octo.dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/rfallow'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /www/images/rfallow_logo.png
logoalt: R-Fallow

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: /rfallow/manual.md
- text: Add a new page
  internal: true
  #url: add-a-new-page
- text: Configure the Guide
  internal: true
  #url: configure-the-guide
- text: GitHub Setup
  internal: true
  #url: github
- text: Create a Glossary
  glossary: true
#- text: Edit this Repo
#  internal: false
#  url: https://github.com/DCgov/guides-template

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: guides-template
  description: 
  url: https://github.com/degi/rfallow

google_analytics_ua: 

# Style Variables
brand_color: "#DA253B"
