layout: page
title: User Manual
permalink: /docs
baseurl: /rfallow # the subpath of your site, e.g. /blog
theme: minima
exclude: ["RFallow_manual.md"]

logourl: /www/images/rfallow_logo.png
logoalt: R-Fallow
